version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@architect/architect"
    versions:
    - 8.4.10
    - 8.4.11
    - 8.4.7
    - 8.4.8
    - 8.4.9
    - 8.5.0
    - 8.5.1
    - 8.5.2
    - 8.5.3
    - 8.5.4
    - 8.5.5
    - 8.5.6
    - 8.5.7
    - 8.5.8
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: docsify
    versions:
    - 4.12.0
  - dependency-name: slugify
    versions:
    - 1.4.6
    - 1.4.7
  - dependency-name: "@11ty/eleventy-plugin-rss"
    versions:
    - 1.1.0
  - dependency-name: docsify-cli
    versions:
    - 4.4.2
  - dependency-name: elliptic
    versions:
    - 6.5.3
