- name: package-update
  uses: taichi/actions-package-update@master
  env:
    AUTHOR_EMAIL: john@example.com
    AUTHOR_NAME: John
    EXECUTE: "true"
    GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    UPDATE_COMMAND: yarn
  with:
    args: upgrade --latest
